# Generated by Django 5.2.6 on 2025-09-18 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProsedurPilihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True, verbose_name='Nama Prosedur')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_open', models.BooleanField(default=True, verbose_name='Permohonan Dibuka')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mod Selenggaraan Aktif')),
                ('papan_notis', models.TextField(blank=True, help_text='Maklumat yang akan dipaparkan di halaman log masuk.', null=True, verbose_name='Teks Papan Notis')),
            ],
            options={
                'verbose_name': 'Tetapan Laman',
                'verbose_name_plural': 'Tetapan Laman',
            },
        ),
        migrations.CreateModel(
            name='Permohonan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemohon', models.CharField(max_length=255)),
                ('no_kp', models.CharField(max_length=15, verbose_name='No K/P')),
                ('tarikh_mula_bertugas', models.DateField(verbose_name='Tarikh mula bertugas di jabatan sekarang')),
                ('no_sijil_amalan', models.CharField(max_length=100, verbose_name='No. Sijil Amalan Tahunan')),
                ('jenis_permohonan', models.CharField(choices=[('Baru', 'Permohonan Baru (Privileging)'), ('Penambahan', 'Permohonan Penambahan (Privileging Addition)'), ('Ulangan', 'Permohonan Ulangan (Re-Privileging)'), ('Ulangan + Tambah', 'Permohonan Ulangan bersama penambahan prosedur baru'), ('Ulangan + Kurang', 'Permohonan Ulangan bersama pengurangan prosedur baru')], max_length=50)),
                ('kategori_pemohon', models.CharField(choices=[('Pakar Perubatan / Pergigian', 'Pakar Perubatan / Pergigian'), ('Pegawai Perubatan / Pergigian', 'Pegawai Perubatan / Pergigian'), ('Paramedik', 'Paramedik'), ('Anggota Kesihatan Bersekutu', 'Anggota Kesihatan Bersekutu'), ('Pegawai Farmasi', 'Pegawai Farmasi'), ('Penolong Pegawai Farmasi', 'Penolong Pegawai Farmasi'), ('Lain-lain', 'Jawatan lain-lain')], max_length=100)),
                ('tarikh_borang_dihantar', models.DateField(auto_now_add=True)),
                ('status_sokongan_kj', models.CharField(choices=[('Menunggu', 'Menunggu Semakan'), ('Menyokong', 'Menyokong'), ('Tidak Menyokong', 'Tidak Menyokong')], default='Menunggu', max_length=20, verbose_name='Status Sokongan Ketua Jabatan')),
                ('ulasan_kj', models.TextField(blank=True, null=True, verbose_name='Ulasan Ketua Jabatan')),
                ('nama_kj', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Ketua Jabatan')),
                ('jawatan_kj', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jawatan Ketua Jabatan')),
                ('tarikh_sokongan_kj', models.DateField(blank=True, null=True, verbose_name='Tarikh Sokongan Ketua Jabatan')),
                ('keputusan_jawatanankuasa', models.CharField(choices=[('Menunggu', 'Menunggu Keputusan'), ('Ya', 'Diluluskan'), ('Tidak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('tarikh_keputusan', models.DateField(blank=True, null=True, verbose_name='Tarikh Keputusan')),
                ('tarikh_sah_sehingga', models.DateField(blank=True, null=True, verbose_name='Tarikh Sah Sehingga')),
                ('no_siri_sijil', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='No Siri Sijil')),
                ('gred', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='permohonan.gred', verbose_name='Gred')),
                ('jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='permohonan.jabatan')),
                ('jawatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='permohonan.jawatan', verbose_name='Jawatan')),
                ('pemohon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kelayakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelayakan', models.CharField(max_length=255, verbose_name='Kelayakan (Ijazah, Master dll.)')),
                ('universiti', models.CharField(max_length=255)),
                ('tahun_lulus', models.IntegerField(verbose_name='Tahun Lulus')),
                ('salinan_sijil', models.FileField(upload_to='sijil_kelayakan/', verbose_name='Salinan Sijil')),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelayakan', to='permohonan.permohonan')),
            ],
        ),
        migrations.CreateModel(
            name='ProsedurDimohon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_prosedur', models.CharField(choices=[('Core', 'Core Procedure'), ('Specialised', 'Specialised Procedure'), ('Addition', 'Addition Procedure'), ('Reduction', 'Reduction Procedure'), ('Digugurkan', 'Prosedur Digugurkan')], max_length=20)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosedur', to='permohonan.permohonan')),
                ('nama_prosedur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='permohonan.prosedurpilihan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_profil', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permohonan.jabatan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
