# Generated by Django 5.2.6 on 2025-09-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan',
            name='keputusan_jawatanankuasa',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Keputusan'), ('Ya', 'Diluluskan'), ('Tidak', 'Ditolak')], default='Menunggu', max_length=20, verbose_name='Keputusan Pengarah'),
        ),
    ]
