# Generated by Django 5.2.6 on 2025-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan', '0002_alter_permohonan_keputusan_jawatanankuasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SijilTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text="Nama untuk templat ini (cth: 'Templat Rasmi 2024')", max_length=100)),
                ('html_content', models.TextField(help_text='Kod HTML penuh untuk templat sijil.')),
                ('is_active', models.BooleanField(default=False, help_text='Tandakan jika ini adalah templat yang sedang digunakan. Hanya satu templat boleh aktif pada satu masa.')),
                ('tarikh_dicipta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Templat Sijil',
                'verbose_name_plural': 'Templat Sijil',
            },
        ),
    ]
