# Generated by Django 5.2.6 on 2025-09-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permohonan', '0003_sijiltemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sub-Kategori Pemohon',
                'verbose_name_plural': 'Sub-Kategori Pemohon',
            },
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='kategori_bawahan',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Pakar HWKKS', 'Pakar HWKKS'), ('Pakar KKM Lain', 'Pakar KKM dari Hospital lain selain HWKKS'), ('Pakar Bukan KKM', 'Pakar daripada institusi selain KKM'), ('Lantikan Baru', 'Lantikan baru/ bertukar masuk'), ('Ada Credentialing', 'Ada Credentialing'), ('Ada Post Basic', 'Ada Post Basic')], editable=False, max_length=100, null=True, verbose_name='Sub-Kategori Pemohon (Lama)'),
        ),
        migrations.AddField(
            model_name='permohonan',
            name='sub_kategori',
            field=models.ManyToManyField(blank=True, to='permohonan.subkategori', verbose_name='Sub-Kategori Pemohon'),
        ),
    ]
