# Generated by Django 5.2.6 on 2025-09-26 03:21

from django.db import migrations

KATEGORI_BAWAHAN_CHOICES = [
    'Pakar HWKKS',
    'Pakar KKM dari Hospital lain selain HWKKS',
    'Pakar Bukan KKM',
    'Lantikan baru/ bertukar masuk',
    'Ada Credentialing',
    'Ada Post Basic',
]

def populate_subkategori(apps, schema_editor):
    SubKategori = apps.get_model('permohonan', 'SubKategori')
    for choice in KATEGORI_BAWAHAN_CHOICES:
        SubKategori.objects.get_or_create(nama=choice)

def reverse_populate_subkategori(apps, schema_editor):
    SubKategori = apps.get_model('permohonan', 'SubKategori')
    SubKategori.objects.filter(nama__in=KATEGORI_BAWAHAN_CHOICES).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('permohonan', '0004_subkategori_alter_permohonan_kategori_bawahan_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_subkategori, reverse_code=reverse_populate_subkategori),
    ]
